name: Deploy Backend to SmarterASP

on:
  push:
    branches:
      - master # HOẶC master (Tùy thuộc vào tên nhánh của bạn)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Tải code từ GitHub về
      uses: actions/checkout@v3

    - name: 2. Cài đặt môi trường .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: 3. Đóng gói dự án (Publish)
      run: dotnet publish -c Release -o ./publish_output

    - name: 4. Bật chế độ bảo trì (Mở khóa file DLL)
      run: |
        echo "Hệ thống đang cập nhật, vui lòng quay lại sau ít phút..." > app_offline.htm
        curl -T app_offline.htm ftp://${{ secrets.FTP_SERVER }}/site1/app_offline.htm --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
        sleep 5 
        # Lệnh sleep 5 giúp server có 5 giây để kịp thời đóng ứng dụng và nhả file

    - name: 5. Đẩy code mới lên SmarterASP qua FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish_output/
        server-dir: /site1/

    - name: 6. Khởi động lại server (Xóa file bảo trì)
      run: |
        curl ftp://${{ secrets.FTP_SERVER }}/site1/ --user ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} -Q "-DELE /site1/app_offline.htm"